x-backend-service: &backend-service
  build:
    context: ./backend
    dockerfile: Dockerfile
  volumes:
    - ./backend:/app
  command: ["air", "-c", ".air.toml"]
  image: my-app-image

services:
  management-api:
    <<: *backend-service
    environment:
      - SERVICE_NAME=management-api
    ports:
      - "8080:8080"
  portal-api:
    <<: *backend-service
    environment:
      - SERVICE_NAME=portal-api
    ports:
      - "8081:8080"
  worker:
    <<: *backend-service
    environment:
      - SERVICE_NAME=worker
    ports:
      - "8082:8080"